import { create } from "zustand";
const chats = [
  {
    userId: 1,
    chatId: 1,
    name: "Semalign M",
    avatar: "https://i.pravatar.cc/40?img=1",
    online: true,
    unreadCount: 2,
    email: "Sem@example.com",
    bio: "Jireh",
    username: "qwerty",
    messages: [
      {
        messageId: 101,
        sender: "Semalign M",
        text: "Hello There, I have seen Saron today and I'm so excited",
        time: "10:30 PM",
        type: "text",
      },
      {
        messageId: 102,
        sender: "You",
        text: "Really? Where did you see her?",
        time: "10:32 PM",
        type: "text",
      },
      {
        messageId: 103,
        sender: "Semalign M",
        text: "At the new coffee shop near the park! She was with her friend.",
        time: "10:33 PM",
        type: "text",
      },
      {
        messageId: 104,
        sender: "You",
        text: "That's awesome! You get lucky today.",
        time: "10:35 PM",
        type: "text",
      },
    ],
  },
  {
    userId: 2,
    chatId: 2,
    name: "Mikias B",
    avatar: "https://i.pravatar.cc/40?img=3",
    online: false,
    unreadCount: 1,
    email: "thomas@example.com",
    bio: "God is Great",
    username: "thomas",
    messages: [
      {
        messageId: 201,
        sender: "Mikias B",
        text: "Yo, How are you doing?",
        time: "10:30 PM",
        type: "text",
      },
      {
        messageId: 202,
        sender: "You",
        text: "I'm good! Just finished that project we talked about.",
        time: "10:31 PM",
        type: "text",
      },
      {
        messageId: 203,
        sender: "Mikias B",
        text: "Nice! Let's grab lunch tomorrow to celebrate.",
        time: "10:33 PM",
        type: "text",
      },
      {
        messageId: 204,
        sender: "You",
        text: "Deal. How about that sushi place?",
        time: "10:34 PM",
        type: "text",
      },
      {
        messageId: 205,
        sender: "Mikias B",
        text: "Sounds perfect! See you at noon.",
        time: "10:35 PM",
        type: "text",
      },
      {
        messageId: 206,
        sender: "You",
        text: "Looking forward to it!",
        time: "10:36 PM",
        type: "text",
      },
      {
        messageId: 207,
        sender: "Mikias B",
        text: "By the way, did you finish that book I lent you?",
        time: "10:37 PM",
        type: "text",
      },
      {
        messageId: 208,
        sender: "You",
        text: "Not yet, but I'm almost done!",
        time: "10:38 PM",
        type: "text",
      },
      {
        messageId: 209,
        sender: "Mikias B",
        text: "No worries! Take your time.",
        time: "10:39 PM",
        type: "text",
      },
      {
        messageId: 210,
        sender: "You",
        text: "Thanks! I appreciate it.",
        time: "10:40 PM",
        type: "text",
      },
      {
        messageId: 211,
        sender: "Mikias B",
        text: "Alright, see you tomorrow!",
        time: "10:41 PM",
        type: "text",
      },
      {
        messageId: 212,
        sender: "You",
        text: "See you!",
        time: "10:42 PM",
        type: "text",
      },
      {
        messageId: 213,
        sender: "Mikias B",
        text: "Take care!",
        time: "10:43 PM",
        type: "text",
      },
      {
        messageId: 214,
        sender: "You",
        text: "You too!",
        time: "10:44 PM",
        type: "text",
      },
    ],
  },

  {
    userId: 3,
    chatId: 3,
    name: "Liya T",
    avatar: "https://i.pravatar.cc/40?img=5",
    online: true,
    unreadCount: 0,
    email: "liya@example.com",
    bio: "UX Designer",
    username: "liyaDesigns",
    messages: [
      {
        messageId: 301,
        sender: "Liya T",
        text: "Hey! I sent you the new wireframes.",
        time: "09:00 AM",
        type: "text",
      },
      {
        messageId: 302,
        sender: "You",
        text: "Thanks! Reviewing them now.",
        time: "09:02 AM",
        type: "text",
      },
    ],
  },
  {
    userId: 4,
    chatId: 4,
    name: "Nahom Y",
    avatar: "https://i.pravatar.cc/40?img=8",
    online: false,
    unreadCount: 5,
    email: "nahom@example.com",
    bio: "Backend Developer",
    username: "nahom.codes",
    messages: [
      {
        messageId: 401,
        sender: "Nahom Y",
        text: "Don't forget the deployment meeting at 3 PM.",
        time: "11:15 AM",
        type: "text",
      },
      {
        messageId: 402,
        sender: "You",
        text: "Got it! Thanks for the reminder.",
        time: "11:16 AM",
        type: "text",
      },
    ],
  },
  {
    userId: 5,
    chatId: 5,
    name: "Ruth A",
    avatar: "https://i.pravatar.cc/40?img=9",
    online: true,
    unreadCount: 0,
    email: "ruth@example.com",
    bio: "Nature Lover 🌿",
    username: "ruthie",
    messages: [
      {
        messageId: 501,
        sender: "Ruth A",
        text: "Hiking trip this weekend?",
        time: "07:30 PM",
        type: "text",
      },
      {
        messageId: 502,
        sender: "You",
        text: "Absolutely! Let’s plan the route.",
        time: "07:31 PM",
        type: "text",
      },
    ],
  },
  {
    userId: 6,
    chatId: 6,
    name: "Eden G",
    avatar: "https://i.pravatar.cc/40?img=11",
    online: false,
    unreadCount: 3,
    email: "eden@example.com",
    bio: "Photographer & Traveler",
    username: "edenShots",
    messages: [
      {
        messageId: 601,
        sender: "Eden G",
        text: "Uploaded the new album to the drive.",
        time: "03:45 PM",
        type: "text",
      },
      {
        messageId: 602,
        sender: "You",
        text: "Awesome! I’ll check them out tonight.",
        time: "03:46 PM",
        type: "text",
      },
    ],
  },
  {
    userId: 7,
    chatId: 7,
    name: "Kalkidan Z",
    avatar: "https://i.pravatar.cc/40?img=12",
    online: true,
    unreadCount: 0,
    email: "kalkidan@example.com",
    bio: "Coffee Addict ☕",
    username: "kalki_z",
    messages: [
      {
        messageId: 701,
        sender: "Kalkidan Z",
        text: "The cafe we talked about is finally open!",
        time: "06:10 PM",
        type: "text",
      },
      {
        messageId: 702,
        sender: "You",
        text: "Let’s go this weekend?",
        time: "06:11 PM",
        type: "text",
      },
    ],
  },
  {
    userId: 8,
    chatId: 8,
    name: "Daniel T",
    avatar: "https://i.pravatar.cc/40?img=15",
    online: false,
    unreadCount: 2,
    email: "daniel@example.com",
    bio: "Full Stack Dev",
    username: "danDev",
    messages: [
      {
        messageId: 801,
        sender: "Daniel T",
        text: "Sent a PR for the bug fix.",
        time: "02:20 PM",
        type: "text",
      },
      {
        messageId: 802,
        sender: "You",
        text: "Merged! Thanks for the quick turnaround.",
        time: "02:21 PM",
        type: "text",
      },
    ],
  },
];

const useMessageStore = create((set) => ({
  messages: [],
  selectedChat: null,

  fetchChat: async () => {
    try {
      setTimeout(() => {
        set({ messages: chats });
      }, 1000);
    } catch (error) {
      console.error("Error fetching messages:", error);
    }
  },
  addMessage: (message) =>
    set((state) => ({ messages: [...state.messages, message] })),
  removeMessage: (id) =>
    set((state) => ({
      messages: state.messages.filter((msg) => msg.id !== id),
    })),
}));

export default useMessageStore;
